addSbtPlugin("org.typelevel"     % "sbt-fs2-grpc"        % "2.7.4")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"         % "1.13.2")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "2.1.5")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker"          % "1.11.0")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.9.16")
